// Generated by scripts/generate_swift_contracts.py. Do not edit by hand.
import Foundation

struct StoredAPIKey: Codable {
    var id: String
    var maskedKey: String
    var createdAt: String?

    enum CodingKeys: String, CodingKey {
        case id
        case maskedKey = "masked_key"
        case createdAt = "created_at"
    }
}

struct ProviderConfig: Codable {
    var modelId: String?
    var baseUrl: String?
    var configured: Bool
    var apiKeys: [StoredAPIKey]?
    var activeApiKeyId: String?

    enum CodingKeys: String, CodingKey {
        case modelId = "model_id"
        case baseUrl = "base_url"
        case configured
        case apiKeys = "api_keys"
        case activeApiKeyId = "active_api_key_id"
    }
}

struct GatewayConfig: Codable {
    var activeProviderId: String?
    var activeModelId: String?
    var activeModelVision: Bool
    var providers: [String: ProviderConfig]

    enum CodingKeys: String, CodingKey {
        case activeProviderId = "active_provider_id"
        case activeModelId = "active_model_id"
        case activeModelVision = "active_model_vision"
        case providers
    }
}

struct SettingsRequest: Codable {
    var providerId: String
    var modelId: String
    var apiKey: String?
    var apiKeyId: String?
    var baseUrl: String?
    var awsAccessKey: String?
    var awsSecretKey: String?
    var region: String?

    enum CodingKeys: String, CodingKey {
        case providerId = "provider_id"
        case modelId = "model_id"
        case apiKey = "api_key"
        case apiKeyId = "api_key_id"
        case baseUrl = "base_url"
        case awsAccessKey = "aws_access_key"
        case awsSecretKey = "aws_secret_key"
        case region
    }
}

struct VerifyRequest: Codable {
    var providerId: String
    var apiKey: String?
    var apiKeyId: String?
    var baseUrl: String?
    var modelId: String?
    var awsAccessKey: String?
    var awsSecretKey: String?
    var region: String?

    enum CodingKeys: String, CodingKey {
        case providerId = "provider_id"
        case apiKey = "api_key"
        case apiKeyId = "api_key_id"
        case baseUrl = "base_url"
        case modelId = "model_id"
        case awsAccessKey = "aws_access_key"
        case awsSecretKey = "aws_secret_key"
        case region
    }
}

struct VerifyResponse: Codable {
    var status: String?
    var models: [String]?
    var detail: String?
}

struct ModelSource: Codable {
    var source: String
    var providerId: String?
    var modelId: String
    var repoId: String?
    var displayName: String
    var providerDisplayName: String?
    var supportsVision: Bool?
    var configured: Bool?
    var loaded: Bool?

    enum CodingKeys: String, CodingKey {
        case source
        case providerId = "provider_id"
        case modelId = "model_id"
        case repoId = "repo_id"
        case displayName = "display_name"
        case providerDisplayName = "provider_display_name"
        case supportsVision = "supports_vision"
        case configured
        case loaded
    }
}

struct GatewayDetailResponse: Codable {
    var status: String?
    var detail: String?
    var active: ModelSource?
    var provider: String?
    var model: String?
    var activeApiKeyId: String?

    enum CodingKeys: String, CodingKey {
        case status
        case detail
        case active
        case provider
        case model
        case activeApiKeyId = "active_api_key_id"
    }
}

struct AvailableModelsResponse: Codable {
    var active: ModelSource?
    var sources: [ModelSource]
    var mlxAvailable: Bool
    var modelsDir: String

    enum CodingKeys: String, CodingKey {
        case active
        case sources
        case mlxAvailable = "mlx_available"
        case modelsDir = "models_dir"
    }
}

struct ActivateModelRequest: Codable {
    var source: String
    var modelId: String
    var providerId: String?

    enum CodingKeys: String, CodingKey {
        case source
        case modelId = "model_id"
        case providerId = "provider_id"
    }
}

struct LocalModelManifest: Codable {
    var id: String
    var kind: String?
    var engine: String?
    var repoId: String
    var displayName: String
    var revision: String?
    var supportsVision: Bool?
    var installedAt: String?
    var localPath: String

    enum CodingKeys: String, CodingKey {
        case id
        case kind
        case engine
        case repoId = "repo_id"
        case displayName = "display_name"
        case revision
        case supportsVision = "supports_vision"
        case installedAt = "installed_at"
        case localPath = "local_path"
    }
}

struct RecommendedLocalModel: Codable {
    var repoId: String
    var displayName: String
    var notes: String?

    enum CodingKeys: String, CodingKey {
        case repoId = "repo_id"
        case displayName = "display_name"
        case notes
    }
}

struct ModelDownloadStatus: Codable {
    var modelId: String
    var repoId: String
    var displayName: String?
    var revision: String?
    var status: String
    var error: String?
    var localPath: String?

    enum CodingKeys: String, CodingKey {
        case modelId = "model_id"
        case repoId = "repo_id"
        case displayName = "display_name"
        case revision
        case status
        case error
        case localPath = "local_path"
    }
}

struct ModelDownloadStatusResponse: Codable {
    var downloads: [ModelDownloadStatus]
}

struct LocalModelsResponse: Codable {
    var modelsDir: String
    var installed: [LocalModelManifest]
    var recommended: [RecommendedLocalModel]
    var activeProviderId: String?
    var activeModelId: String?
    var mlxAvailable: Bool
    var huggingfaceHubAvailable: Bool
    var downloads: [ModelDownloadStatus]

    enum CodingKeys: String, CodingKey {
        case modelsDir = "models_dir"
        case installed
        case recommended
        case activeProviderId = "active_provider_id"
        case activeModelId = "active_model_id"
        case mlxAvailable = "mlx_available"
        case huggingfaceHubAvailable = "huggingface_hub_available"
        case downloads
    }
}

struct ModelDownloadRequest: Codable {
    var repoId: String
    var displayName: String?
    var revision: String?

    enum CodingKeys: String, CodingKey {
        case repoId = "repo_id"
        case displayName = "display_name"
        case revision
    }
}

struct ModelActionRequest: Codable {
    var modelId: String

    enum CodingKeys: String, CodingKey {
        case modelId = "model_id"
    }
}

struct RecurrencePayload: Codable {
    var frequency: String
    var interval: Int?
    var weekdays: [String]?
    var endDate: String?
    var occurrenceCount: Int?

    enum CodingKeys: String, CodingKey {
        case frequency
        case interval
        case weekdays
        case endDate = "end_date"
        case occurrenceCount = "occurrence_count"
    }
}

struct CalendarPayload: Codable {
    var title: String?
    var notes: String?
    var location: String?
    var startTime: String?
    var endTime: String?
    var isAllDay: Bool?
    var needsDuration: Bool?
    var recurrence: RecurrencePayload?
    var travelTimeMinutes: Int?
    var alertMinutesBeforeStart: Int?
    var calendarName: String?
    var url: String?

    enum CodingKeys: String, CodingKey {
        case title
        case notes
        case location
        case startTime = "start_time"
        case endTime = "end_time"
        case isAllDay = "is_all_day"
        case needsDuration = "needs_duration"
        case recurrence
        case travelTimeMinutes = "travel_time_minutes"
        case alertMinutesBeforeStart = "alert_minutes_before_start"
        case calendarName = "calendar_name"
        case url
    }
}

struct ReminderPayload: Codable {
    var title: String?
    var notes: String?
    var location: String?
    var dueDate: String?
    var dueTime: String?
    var recurrence: RecurrencePayload?
    var alertMinutesBeforeDue: Int?
    var listName: String?
    var priority: String?
    var flagged: Bool?
    var url: String?

    enum CodingKeys: String, CodingKey {
        case title
        case notes
        case location
        case dueDate = "due_date"
        case dueTime = "due_time"
        case recurrence
        case alertMinutesBeforeDue = "alert_minutes_before_due"
        case listName = "list_name"
        case priority
        case flagged
        case url
    }
}

struct ConflictInfo: Codable {
    var id: String
    var title: String
    var startTime: String
    var endTime: String
    var calendarName: String?

    enum CodingKeys: String, CodingKey {
        case id
        case title
        case startTime = "start_time"
        case endTime = "end_time"
        case calendarName = "calendar_name"
    }
}

struct AppliedPreference: Codable {
    var field: String
    var value: String
    var label: String
    var source: String
    var message: String
}

struct RecognitionCandidate: Codable {
    var id: String
    var kind: String
    var calendar: CalendarPayload?
    var reminder: ReminderPayload?
    var confidence: Double?
    var evidence: String?
    var missingFields: [String]?
    var clarificationQuestion: String?
    var conflicts: [ConflictInfo]?
    var status: String?
    var appliedPreferences: [AppliedPreference]?

    enum CodingKeys: String, CodingKey {
        case id
        case kind
        case calendar
        case reminder
        case confidence
        case evidence
        case missingFields = "missing_fields"
        case clarificationQuestion = "clarification_question"
        case conflicts
        case status
        case appliedPreferences = "applied_preferences"
    }
}

struct ChatRequest: Codable {
    var message: String?
    var image: String?
    var inputMode: String?
    var sessionId: String?
    var formData: [String: String]?
    var userAction: String?
    var originalResult: [String: String]?
    var corrections: [String: String]?
    var selectedCandidateIds: [String]?

    enum CodingKeys: String, CodingKey {
        case message
        case image
        case inputMode = "input_mode"
        case sessionId = "session_id"
        case formData = "form_data"
        case userAction = "user_action"
        case originalResult = "original_result"
        case corrections
        case selectedCandidateIds = "selected_candidate_ids"
    }
}

struct AssistantChatRequest: Codable {
    var message: String?
    var sessionId: String?

    enum CodingKeys: String, CodingKey {
        case message
        case sessionId = "session_id"
    }
}

struct AssistantDateRange: Codable {
    var startDate: String?
    var endDate: String?
    var label: String?

    enum CodingKeys: String, CodingKey {
        case startDate = "start_date"
        case endDate = "end_date"
        case label
    }
}

struct AssistantActionTarget: Codable {
    var itemKind: String?
    var titleKeywords: [String]?
    var dateRange: AssistantDateRange?
    var timeOfDay: String?
    var timePeriod: String?
    var rawText: String?

    enum CodingKeys: String, CodingKey {
        case itemKind = "item_kind"
        case titleKeywords = "title_keywords"
        case dateRange = "date_range"
        case timeOfDay = "time_of_day"
        case timePeriod = "time_period"
        case rawText = "raw_text"
    }
}

struct AssistantOperationPatch: Codable {
    var shiftMinutes: Int?
    var alertMinutesBefore: Int?
    var newStartTime: String?
    var newEndTime: String?
    var newDueDate: String?
    var newDueTime: String?
    var title: String?
    var location: String?

    enum CodingKeys: String, CodingKey {
        case shiftMinutes = "shift_minutes"
        case alertMinutesBefore = "alert_minutes_before"
        case newStartTime = "new_start_time"
        case newEndTime = "new_end_time"
        case newDueDate = "new_due_date"
        case newDueTime = "new_due_time"
        case title
        case location
    }
}

struct AssistantMemoryAction: Codable {
    var tool: String
    var arguments: [String: String]?
    var confidence: Double?
    var requiresConfirmation: Bool?

    enum CodingKeys: String, CodingKey {
        case tool
        case arguments
        case confidence
        case requiresConfirmation = "requires_confirmation"
    }
}

struct AssistantNotePayload: Codable {
    var title: String
    var content: String
}

struct AssistantActionPlan: Codable {
    var action: String
    var reply: String?
    var clarificationQuestion: String?
    var target: AssistantActionTarget?
    var patch: AssistantOperationPatch?
    var note: AssistantNotePayload?
    var preferenceValues: [String: String]?
    var memoryActions: [AssistantMemoryAction]?
    var confirmationRequired: Bool?

    enum CodingKeys: String, CodingKey {
        case action
        case reply
        case clarificationQuestion = "clarification_question"
        case target
        case patch
        case note
        case preferenceValues = "preference_values"
        case memoryActions = "memory_actions"
        case confirmationRequired = "confirmation_required"
    }
}

struct AgentResponse: Codable {
    var type: String
    var sessionId: String?
    var candidates: [RecognitionCandidate]?
    var reply: String?
    var error: String?
    var missingFields: [String]?
    var prefilled: [String: String]?

    enum CodingKeys: String, CodingKey {
        case type
        case sessionId = "session_id"
        case candidates
        case reply
        case error
        case missingFields = "missing_fields"
        case prefilled
    }
}

struct AssistantChatResponse: Codable {
    var sessionId: String
    var reply: String
    var action: String
    var agentResponse: AgentResponse?
    var actionPlan: AssistantActionPlan?
    var updatedPreferences: [String: String]?
    var memoryUpdates: [[String: String]]?
    var error: String?

    enum CodingKeys: String, CodingKey {
        case sessionId = "session_id"
        case reply
        case action
        case agentResponse = "agent_response"
        case actionPlan = "action_plan"
        case updatedPreferences = "updated_preferences"
        case memoryUpdates = "memory_updates"
        case error
    }
}

struct CalendarEventSnapshot: Codable {
    var id: String
    var title: String
    var startTime: String
    var endTime: String
    var isAllDay: Bool?
    var location: String?
    var calendarName: String?
    var alertMinutesBeforeStart: Int?

    enum CodingKeys: String, CodingKey {
        case id
        case title
        case startTime = "start_time"
        case endTime = "end_time"
        case isAllDay = "is_all_day"
        case location
        case calendarName = "calendar_name"
        case alertMinutesBeforeStart = "alert_minutes_before_start"
    }
}

struct ReminderSnapshot: Codable {
    var id: String
    var title: String
    var dueDate: String?
    var dueTime: String?
    var isCompleted: Bool?
    var priority: Int?
    var listName: String?
    var alertMinutesBeforeDue: Int?

    enum CodingKeys: String, CodingKey {
        case id
        case title
        case dueDate = "due_date"
        case dueTime = "due_time"
        case isCompleted = "is_completed"
        case priority
        case listName = "list_name"
        case alertMinutesBeforeDue = "alert_minutes_before_due"
    }
}

struct HeartbeatTickRequest: Codable {
    var now: String
    var appActive: Bool
    var todayEvents: [CalendarEventSnapshot]?
    var tomorrowEvents: [CalendarEventSnapshot]?
    var incompleteReminders: [ReminderSnapshot]?

    enum CodingKeys: String, CodingKey {
        case now
        case appActive = "app_active"
        case todayEvents = "today_events"
        case tomorrowEvents = "tomorrow_events"
        case incompleteReminders = "incomplete_reminders"
    }
}

struct ProactiveEvent: Codable {
    var id: String
    var triggerType: String
    var title: String
    var body: String
    var primaryButton: String?
    var snoozeOptions: [Int]?

    enum CodingKeys: String, CodingKey {
        case id
        case triggerType = "trigger_type"
        case title
        case body
        case primaryButton = "primary_button"
        case snoozeOptions = "snooze_options"
    }
}

struct HeartbeatTickResponse: Codable {
    var events: [ProactiveEvent]?
}

struct MemoryStatus: Codable {
    var directory: String
    var files: [String: Bool]
    var promptContext: String
    var recentLearnings: String?
    var recentErrors: String?

    enum CodingKeys: String, CodingKey {
        case directory
        case files
        case promptContext = "prompt_context"
        case recentLearnings = "recent_learnings"
        case recentErrors = "recent_errors"
    }
}

struct MemoryFile: Codable {
    var id: String
    var filename: String
    var title: String
    var editable: Bool
    var content: String?
    var truncated: Bool?
    var byteSize: Int?

    enum CodingKeys: String, CodingKey {
        case id
        case filename
        case title
        case editable
        case content
        case truncated
        case byteSize = "byte_size"
    }
}

struct MemoryFilesResponse: Codable {
    var files: [MemoryFile]?
}

struct MemoryFileUpdateRequest: Codable {
    var content: String
}

struct MemoryFileUpdateResponse: Codable {
    var file: MemoryFile
}

struct PreferenceMeta: Codable {
    var source: String?
    var confidence: Double?
    var observations: Int?
    var updatedAt: String?
    var cleared: Bool?

    enum CodingKeys: String, CodingKey {
        case source
        case confidence
        case observations
        case updatedAt = "updated_at"
        case cleared
    }
}

struct PreferenceStatValue: Codable {
    var count: Int?
    var sessions: [String]?
    var lastSeen: String?

    enum CodingKeys: String, CodingKey {
        case count
        case sessions
        case lastSeen = "last_seen"
    }
}

struct MemoryPreferencesResponse: Codable {
    var preferences: [String: String]
    var preferenceMeta: [String: PreferenceMeta]?
    var preferenceStats: [String: [String: PreferenceStatValue]]?

    enum CodingKeys: String, CodingKey {
        case preferences
        case preferenceMeta = "preference_meta"
        case preferenceStats = "preference_stats"
    }
}

struct MemoryPreferencesPatch: Codable {
    var calendarDefaultDurationMinutes: Int?
    var calendarDefaultAlertMinutes: Int?
    var reminderDefaultAlertMinutes: Int?
    var reminderDefaultDueTime: String?
    var reminderDefaultPriorityForDeadline: String?

    enum CodingKeys: String, CodingKey {
        case calendarDefaultDurationMinutes = "calendar_default_duration_minutes"
        case calendarDefaultAlertMinutes = "calendar_default_alert_minutes"
        case reminderDefaultAlertMinutes = "reminder_default_alert_minutes"
        case reminderDefaultDueTime = "reminder_default_due_time"
        case reminderDefaultPriorityForDeadline = "reminder_default_priority_for_deadline"
    }
}

struct MemoryFeedbackRequest: Codable {
    var action: String
    var sessionId: String?
    var candidateId: String?
    var candidateKind: String?
    var title: String?
    var status: String?
    var modified: Bool?
    var note: String?
    var finalCandidate: RecognitionCandidate?

    enum CodingKeys: String, CodingKey {
        case action
        case sessionId = "session_id"
        case candidateId = "candidate_id"
        case candidateKind = "candidate_kind"
        case title
        case status
        case modified
        case note
        case finalCandidate = "final_candidate"
    }
}

struct MemoryFeedbackResponse: Codable {
    var status: String
}
