#!/usr/bin/env python3
from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
PYTHON_DIR = ROOT / "Python"
OUT = ROOT / "Jarvis" / "Models" / "GeneratedContracts.swift"


def camel(name: str) -> str:
    parts = name.split("_")
    return parts[0] + "".join(part[:1].upper() + part[1:] for part in parts[1:])


def swift_type(schema: dict[str, Any], required: bool = True) -> str:
    nullable = False
    if "anyOf" in schema:
        options = []
        for item in schema["anyOf"]:
            if item.get("type") == "null":
                nullable = True
            else:
                options.append(item)
        if len(options) != 1:
            raise ValueError(f"Unsupported anyOf schema: {schema}")
        inner = swift_type(options[0], required=True)
        return inner + ("?" if nullable or not required else "")

    if "allOf" in schema:
        if len(schema["allOf"]) != 1:
            raise ValueError(f"Unsupported allOf schema: {schema}")
        inner = swift_type(schema["allOf"][0], required=True)
        return inner + ("?" if not required else "")

    if "$ref" in schema:
        inner = schema["$ref"].split("/")[-1]
        return inner + ("?" if not required else "")

    if "enum" in schema:
        values = schema["enum"]
        if all(isinstance(v, str) for v in values):
            return "String" + ("?" if not required else "")
        raise ValueError(f"Unsupported enum schema: {schema}")

    typ = schema.get("type")
    if typ == "string":
        inner = "String"
    elif typ == "integer":
        inner = "Int"
    elif typ == "number":
        inner = "Double"
    elif typ == "boolean":
        inner = "Bool"
    elif typ == "array":
        inner = f"[{swift_type(schema.get('items', {'type': 'string'}), required=True)}]"
    elif typ == "object":
        additional = schema.get("additionalProperties")
        if additional is True or additional is None:
            inner = "[String: String]"
        elif isinstance(additional, dict):
            inner = f"[String: {swift_type(additional, required=True)}]"
        else:
            raise ValueError(f"Unsupported object schema: {schema}")
    else:
        raise ValueError(f"Unsupported schema type: {schema}")

    return inner + ("?" if not required else "")


def model_schema(model: type) -> dict[str, Any]:
    return model.model_json_schema(ref_template="#/$defs/{model}")


def generate_model(model: type) -> str:
    schema = model_schema(model)
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = [f"struct {model.__name__}: Codable {{"]

    for name, prop in properties.items():
        lines.append(f"    var {camel(name)}: {swift_type(prop, name in required)}")

    coded = [(name, camel(name)) for name in properties if name != camel(name)]
    if coded:
        lines.append("")
        lines.append("    enum CodingKeys: String, CodingKey {")
        for name, swift_name in properties.items():
            key = camel(name)
            if name == key:
                lines.append(f"        case {key}")
            else:
                lines.append(f"        case {key} = \"{name}\"")
        lines.append("    }")

    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    sys.path.insert(0, str(PYTHON_DIR))
    from contracts import CONTRACT_MODELS

    body = [
        "// Generated by scripts/generate_swift_contracts.py. Do not edit by hand.",
        "import Foundation",
        "",
    ]
    body.extend(generate_model(model) + "\n" for model in CONTRACT_MODELS)
    text = "\n".join(body).rstrip() + "\n"
    OUT.write_text(text, encoding="utf-8")
    print(f"generated {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
