import MapKit
import CoreLocation

class MapKitTool {
    static func search(keyword: String) async -> [LocationResult] {
        let request = MKLocalSearch.Request()
        request.naturalLanguageQuery = keyword
        request.resultTypes = .pointOfInterest

        let search = MKLocalSearch(request: request)
        do {
            let response = try await search.start()
            let userLocation = CLLocation(latitude: 39.9042, longitude: 116.4074) // Beijing fallback
            return response.mapItems.prefix(5).map { item in
                let itemLocation = item.placemark.location
                return LocationResult(
                    name: item.name ?? keyword,
                    address: item.placemark.formattedAddress,
                    latitude: item.placemark.coordinate.latitude,
                    longitude: item.placemark.coordinate.longitude,
                    distance: itemLocation?.distance(from: userLocation)
                )
            }
        } catch {
            return []
        }
    }
}

class LocationMemoryStore {
    private static let directory = FileManager.default.homeDirectoryForCurrentUser
        .appendingPathComponent(".jarvis")
    private static let jsonPath = directory.appendingPathComponent("memory.json")
    private static let markdownPath = directory.appendingPathComponent("memory.md")
    private static let legacyLocationPath = directory.appendingPathComponent("location_aliases.json")

    static func lookup(keyword: String) -> LocationResult? {
        let aliases = loadMemory().locationAliases
        guard let alias = aliases[keyword] else { return nil }
        return LocationResult(
            name: alias.name,
            address: alias.address,
            latitude: alias.latitude,
            longitude: alias.longitude,
            distance: nil
        )
    }

    static func save(keyword: String, result: LocationResult) {
        guard !keyword.isEmpty else { return }
        var memory = loadMemory()
        memory.locationAliases[keyword] = LocationAlias(
            name: result.name,
            address: result.address,
            latitude: result.latitude,
            longitude: result.longitude
        )
        do {
            try FileManager.default.createDirectory(
                at: directory,
                withIntermediateDirectories: true
            )
            let encoder = JSONEncoder()
            encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
            let data = try encoder.encode(memory)
            try data.write(to: jsonPath, options: .atomic)
            try renderMarkdown(memory).write(to: markdownPath, atomically: true, encoding: .utf8)
            try? FileManager.default.setAttributes([.posixPermissions: 0o444], ofItemAtPath: markdownPath.path)
        } catch {
            jlog("[LocationMemory] save failed: \(error.localizedDescription)")
        }
    }

    private static func loadMemory() -> JarvisMemory {
        if let data = try? Data(contentsOf: jsonPath),
           let memory = try? JSONDecoder().decode(JarvisMemory.self, from: data) {
            return memory
        }

        var memory = JarvisMemory()
        if let data = try? Data(contentsOf: legacyLocationPath),
           let aliases = try? JSONDecoder().decode([String: LocationAlias].self, from: data) {
            memory.locationAliases = aliases
        }
        return memory
    }

    private static func renderMarkdown(_ memory: JarvisMemory) -> String {
        var lines: [String] = [
            "# Jarvis Memory",
            "",
            "> Read-only human view. Jarvis writes to `memory.json`; do not edit this file.",
            "",
            "## Preferences",
            "",
        ]

        if memory.preferences.isEmpty {
            lines.append("- No preferences saved yet.")
        } else {
            for key in memory.preferences.keys.sorted() {
                lines.append("- \(key): \(memory.preferences[key]?.markdownDescription ?? "")")
            }
        }

        lines += ["", "## Location Aliases", ""]
        if memory.locationAliases.isEmpty {
            lines.append("- No location aliases saved yet.")
        } else {
            for key in memory.locationAliases.keys.sorted() {
                guard let alias = memory.locationAliases[key] else { continue }
                lines.append("### \(key)")
                lines.append("")
                lines.append("- Name: \(alias.name)")
                if !alias.address.isEmpty {
                    lines.append("- Address: \(alias.address)")
                }
                lines.append("- Latitude: \(alias.latitude)")
                lines.append("- Longitude: \(alias.longitude)")
                lines.append("")
            }
        }

        return lines.joined(separator: "\n") + "\n"
    }
}

private struct JarvisMemory: Codable {
    var preferences: [String: JSONValue] = [:]
    var locationAliases: [String: LocationAlias] = [:]

    enum CodingKeys: String, CodingKey {
        case preferences
        case locationAliases = "location_aliases"
    }
}

private enum JSONValue: Codable {
    case string(String)
    case int(Int)
    case double(Double)
    case bool(Bool)
    case null

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() {
            self = .null
        } else if let value = try? container.decode(Bool.self) {
            self = .bool(value)
        } else if let value = try? container.decode(Int.self) {
            self = .int(value)
        } else if let value = try? container.decode(Double.self) {
            self = .double(value)
        } else {
            self = .string(try container.decode(String.self))
        }
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let value): try container.encode(value)
        case .int(let value): try container.encode(value)
        case .double(let value): try container.encode(value)
        case .bool(let value): try container.encode(value)
        case .null: try container.encodeNil()
        }
    }

    var markdownDescription: String {
        switch self {
        case .string(let value): return value
        case .int(let value): return String(value)
        case .double(let value): return String(value)
        case .bool(let value): return value ? "true" : "false"
        case .null: return "null"
        }
    }
}

private struct LocationAlias: Codable {
    let name: String
    let address: String
    let latitude: Double
    let longitude: Double
}

extension MKPlacemark {
    var formattedAddress: String {
        [subLocality, locality, administrativeArea]
            .compactMap { $0 }
            .joined(separator: " ")
    }
}
